test: on
image: Visual Studio 2022
init:
- cmd: net start MSSQL$SQL2019
- ps: Get-ChildItem -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\' |Where-Object {$_.Name -imatch 'MSSQL[_\d]+\.SQL.*'} | ForEach-Object { Write-Host "Setting $((Get-ItemProperty $_.PSPath).'(default)') to dynamic ports" Set-ItemProperty (Join-Path $_.PSPath 'mssqlserver\supersocketnetlib\tcp\ipall') -Name TcpDynamicPorts -Value '0' Set-ItemProperty (Join-Path $_.PSPath 'mssqlserver\supersocketnetlib\tcp\ipall') -Name TcpPort -Value ([string]::Empty)}
before_build:
- cmd: nuget restore "LazySql.sln"
configuration:
  - APPVEYOR